sudo: required

services:
  - docker

before_install:
  - docker build -t kushal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kushal/react-test npm test

after_success:
  - docker build -t 272990/multi-client ./client
  - docker build -t 272990/multi-nginx ./nginx
  - docker build -t 272990/multi-server ./server
  - docker build -t 272990/multi-worker ./worker

  # Login to docker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io

  # Push repos to docker hub
  - docker push 272990/multi-client
  - docker push 272990/multi-nginx
  - docker push 272990/multi-server
  - docker push 272990/multi-worker
